// Static fallback data for Pokemon TCG sets
export const FALLBACK_SETS = [
  // Scarlet & Violet
  { id: "sv08", name: "Surging Sparks", series: "Scarlet & Violet", releaseDate: "2024/11/08", total: 252, images: { symbol: "https://images.pokemontcg.io/sv8/symbol.png", logo: "https://images.pokemontcg.io/sv8/logo.png" } },
  { id: "sv07", name: "Stellar Crown", series: "Scarlet & Violet", releaseDate: "2024/09/13", total: 175, images: { symbol: "https://images.pokemontcg.io/sv7/symbol.png", logo: "https://images.pokemontcg.io/sv7/logo.png" } },
  { id: "sv06.5", name: "Shrouded Fable", series: "Scarlet & Violet", releaseDate: "2024/08/02", total: 99, images: { symbol: "https://images.pokemontcg.io/sv6pt5/symbol.png", logo: "https://images.pokemontcg.io/sv6pt5/logo.png" } },
  { id: "sv06", name: "Twilight Masquerade", series: "Scarlet & Violet", releaseDate: "2024/05/24", total: 226, images: { symbol: "https://images.pokemontcg.io/sv6/symbol.png", logo: "https://images.pokemontcg.io/sv6/logo.png" } },
  { id: "sv05", name: "Temporal Forces", series: "Scarlet & Violet", releaseDate: "2024/03/22", total: 218, images: { symbol: "https://images.pokemontcg.io/sv5/symbol.png", logo: "https://images.pokemontcg.io/sv5/logo.png" } },
  { id: "sv04.5", name: "Paldean Fates", series: "Scarlet & Violet", releaseDate: "2024/01/26", total: 245, images: { symbol: "https://images.pokemontcg.io/sv4pt5/symbol.png", logo: "https://images.pokemontcg.io/sv4pt5/logo.png" } },
  { id: "sv04", name: "Paradox Rift", series: "Scarlet & Violet", releaseDate: "2023/11/03", total: 266, images: { symbol: "https://images.pokemontcg.io/sv4/symbol.png", logo: "https://images.pokemontcg.io/sv4/logo.png" } },
  { id: "sv03.5", name: "151", series: "Scarlet & Violet", releaseDate: "2023/09/22", total: 207, images: { symbol: "https://images.pokemontcg.io/sv3pt5/symbol.png", logo: "https://images.pokemontcg.io/sv3pt5/logo.png" } },
  { id: "sv03", name: "Obsidian Flames", series: "Scarlet & Violet", releaseDate: "2023/08/11", total: 230, images: { symbol: "https://images.pokemontcg.io/sv3/symbol.png", logo: "https://images.pokemontcg.io/sv3/logo.png" } },
  { id: "sv02", name: "Paldea Evolved", series: "Scarlet & Violet", releaseDate: "2023/06/09", total: 279, images: { symbol: "https://images.pokemontcg.io/sv2/symbol.png", logo: "https://images.pokemontcg.io/sv2/logo.png" } },
  { id: "sv01", name: "Scarlet & Violet", series: "Scarlet & Violet", releaseDate: "2023/03/31", total: 258, images: { symbol: "https://images.pokemontcg.io/sv1/symbol.png", logo: "https://images.pokemontcg.io/sv1/logo.png" } },
  // Sword & Shield
  { id: "swsh12.5", name: "Crown Zenith", series: "Sword & Shield", releaseDate: "2023/01/20", total: 230, images: { symbol: "https://images.pokemontcg.io/swsh12pt5/symbol.png", logo: "https://images.pokemontcg.io/swsh12pt5/logo.png" } },
  { id: "swsh12", name: "Silver Tempest", series: "Sword & Shield", releaseDate: "2022/11/11", total: 245, images: { symbol: "https://images.pokemontcg.io/swsh12/symbol.png", logo: "https://images.pokemontcg.io/swsh12/logo.png" } },
  { id: "swsh11", name: "Lost Origin", series: "Sword & Shield", releaseDate: "2022/09/09", total: 247, images: { symbol: "https://images.pokemontcg.io/swsh11/symbol.png", logo: "https://images.pokemontcg.io/swsh11/logo.png" } },
  { id: "swsh10", name: "Astral Radiance", series: "Sword & Shield", releaseDate: "2022/05/27", total: 246, images: { symbol: "https://images.pokemontcg.io/swsh10/symbol.png", logo: "https://images.pokemontcg.io/swsh10/logo.png" } },
  { id: "swsh9", name: "Brilliant Stars", series: "Sword & Shield", releaseDate: "2022/02/25", total: 216, images: { symbol: "https://images.pokemontcg.io/swsh9/symbol.png", logo: "https://images.pokemontcg.io/swsh9/logo.png" } },
  { id: "swsh8", name: "Fusion Strike", series: "Sword & Shield", releaseDate: "2021/11/12", total: 284, images: { symbol: "https://images.pokemontcg.io/swsh8/symbol.png", logo: "https://images.pokemontcg.io/swsh8/logo.png" } },
  { id: "swsh7", name: "Evolving Skies", series: "Sword & Shield", releaseDate: "2021/08/27", total: 237, images: { symbol: "https://images.pokemontcg.io/swsh7/symbol.png", logo: "https://images.pokemontcg.io/swsh7/logo.png" } },
  { id: "swsh6", name: "Chilling Reign", series: "Sword & Shield", releaseDate: "2021/06/18", total: 233, images: { symbol: "https://images.pokemontcg.io/swsh6/symbol.png", logo: "https://images.pokemontcg.io/swsh6/logo.png" } },
  { id: "swsh5", name: "Battle Styles", series: "Sword & Shield", releaseDate: "2021/03/19", total: 183, images: { symbol: "https://images.pokemontcg.io/swsh5/symbol.png", logo: "https://images.pokemontcg.io/swsh5/logo.png" } },
  { id: "swsh4", name: "Vivid Voltage", series: "Sword & Shield", releaseDate: "2020/11/13", total: 203, images: { symbol: "https://images.pokemontcg.io/swsh4/symbol.png", logo: "https://images.pokemontcg.io/swsh4/logo.png" } },
  { id: "swsh3", name: "Darkness Ablaze", series: "Sword & Shield", releaseDate: "2020/08/14", total: 201, images: { symbol: "https://images.pokemontcg.io/swsh3/symbol.png", logo: "https://images.pokemontcg.io/swsh3/logo.png" } },
  { id: "swsh2", name: "Rebel Clash", series: "Sword & Shield", releaseDate: "2020/05/01", total: 209, images: { symbol: "https://images.pokemontcg.io/swsh2/symbol.png", logo: "https://images.pokemontcg.io/swsh2/logo.png" } },
  { id: "swsh1", name: "Sword & Shield", series: "Sword & Shield", releaseDate: "2020/02/07", total: 216, images: { symbol: "https://images.pokemontcg.io/swsh1/symbol.png", logo: "https://images.pokemontcg.io/swsh1/logo.png" } },
  // Sun & Moon
  { id: "sm12", name: "Cosmic Eclipse", series: "Sun & Moon", releaseDate: "2019/11/01", total: 271, images: { symbol: "https://images.pokemontcg.io/sm12/symbol.png", logo: "https://images.pokemontcg.io/sm12/logo.png" } },
  { id: "sm11", name: "Unified Minds", series: "Sun & Moon", releaseDate: "2019/08/02", total: 258, images: { symbol: "https://images.pokemontcg.io/sm11/symbol.png", logo: "https://images.pokemontcg.io/sm11/logo.png" } },
  { id: "sm10", name: "Unbroken Bonds", series: "Sun & Moon", releaseDate: "2019/05/03", total: 234, images: { symbol: "https://images.pokemontcg.io/sm10/symbol.png", logo: "https://images.pokemontcg.io/sm10/logo.png" } },
  { id: "sm9", name: "Team Up", series: "Sun & Moon", releaseDate: "2019/02/01", total: 196, images: { symbol: "https://images.pokemontcg.io/sm9/symbol.png", logo: "https://images.pokemontcg.io/sm9/logo.png" } },
  { id: "sm8", name: "Lost Thunder", series: "Sun & Moon", releaseDate: "2018/11/02", total: 236, images: { symbol: "https://images.pokemontcg.io/sm8/symbol.png", logo: "https://images.pokemontcg.io/sm8/logo.png" } },
  { id: "sm7", name: "Celestial Storm", series: "Sun & Moon", releaseDate: "2018/08/03", total: 187, images: { symbol: "https://images.pokemontcg.io/sm7/symbol.png", logo: "https://images.pokemontcg.io/sm7/logo.png" } },
  { id: "sm6", name: "Forbidden Light", series: "Sun & Moon", releaseDate: "2018/05/04", total: 146, images: { symbol: "https://images.pokemontcg.io/sm6/symbol.png", logo: "https://images.pokemontcg.io/sm6/logo.png" } },
  { id: "sm5", name: "Ultra Prism", series: "Sun & Moon", releaseDate: "2018/02/02", total: 173, images: { symbol: "https://images.pokemontcg.io/sm5/symbol.png", logo: "https://images.pokemontcg.io/sm5/logo.png" } },
  { id: "sm4", name: "Crimson Invasion", series: "Sun & Moon", releaseDate: "2017/11/03", total: 125, images: { symbol: "https://images.pokemontcg.io/sm4/symbol.png", logo: "https://images.pokemontcg.io/sm4/logo.png" } },
  { id: "sm3", name: "Burning Shadows", series: "Sun & Moon", releaseDate: "2017/08/04", total: 169, images: { symbol: "https://images.pokemontcg.io/sm3/symbol.png", logo: "https://images.pokemontcg.io/sm3/logo.png" } },
  { id: "sm2", name: "Guardians Rising", series: "Sun & Moon", releaseDate: "2017/05/05", total: 169, images: { symbol: "https://images.pokemontcg.io/sm2/symbol.png", logo: "https://images.pokemontcg.io/sm2/logo.png" } },
  { id: "sm1", name: "Sun & Moon", series: "Sun & Moon", releaseDate: "2017/02/03", total: 172, images: { symbol: "https://images.pokemontcg.io/sm1/symbol.png", logo: "https://images.pokemontcg.io/sm1/logo.png" } },
  // XY
  { id: "xy12", name: "Evolutions", series: "XY", releaseDate: "2016/11/02", total: 113, images: { symbol: "https://images.pokemontcg.io/xy12/symbol.png", logo: "https://images.pokemontcg.io/xy12/logo.png" } },
  { id: "xy11", name: "Steam Siege", series: "XY", releaseDate: "2016/08/03", total: 116, images: { symbol: "https://images.pokemontcg.io/xy11/symbol.png", logo: "https://images.pokemontcg.io/xy11/logo.png" } },
  { id: "xy10", name: "Fates Collide", series: "XY", releaseDate: "2016/05/02", total: 129, images: { symbol: "https://images.pokemontcg.io/xy10/symbol.png", logo: "https://images.pokemontcg.io/xy10/logo.png" } },
  { id: "xy9", name: "BREAKpoint", series: "XY", releaseDate: "2016/02/03", total: 126, images: { symbol: "https://images.pokemontcg.io/xy9/symbol.png", logo: "https://images.pokemontcg.io/xy9/logo.png" } },
  { id: "xy8", name: "BREAKthrough", series: "XY", releaseDate: "2015/11/04", total: 165, images: { symbol: "https://images.pokemontcg.io/xy8/symbol.png", logo: "https://images.pokemontcg.io/xy8/logo.png" } },
  { id: "xy7", name: "Ancient Origins", series: "XY", releaseDate: "2015/08/12", total: 101, images: { symbol: "https://images.pokemontcg.io/xy7/symbol.png", logo: "https://images.pokemontcg.io/xy7/logo.png" } },
  { id: "xy6", name: "Roaring Skies", series: "XY", releaseDate: "2015/05/06", total: 112, images: { symbol: "https://images.pokemontcg.io/xy6/symbol.png", logo: "https://images.pokemontcg.io/xy6/logo.png" } },
  { id: "xy5", name: "Primal Clash", series: "XY", releaseDate: "2015/02/04", total: 164, images: { symbol: "https://images.pokemontcg.io/xy5/symbol.png", logo: "https://images.pokemontcg.io/xy5/logo.png" } },
  { id: "xy4", name: "Phantom Forces", series: "XY", releaseDate: "2014/11/05", total: 124, images: { symbol: "https://images.pokemontcg.io/xy4/symbol.png", logo: "https://images.pokemontcg.io/xy4/logo.png" } },
  { id: "xy3", name: "Furious Fists", series: "XY", releaseDate: "2014/08/13", total: 114, images: { symbol: "https://images.pokemontcg.io/xy3/symbol.png", logo: "https://images.pokemontcg.io/xy3/logo.png" } },
  { id: "xy2", name: "Flashfire", series: "XY", releaseDate: "2014/05/07", total: 110, images: { symbol: "https://images.pokemontcg.io/xy2/symbol.png", logo: "https://images.pokemontcg.io/xy2/logo.png" } },
  { id: "xy1", name: "XY", series: "XY", releaseDate: "2014/02/05", total: 146, images: { symbol: "https://images.pokemontcg.io/xy1/symbol.png", logo: "https://images.pokemontcg.io/xy1/logo.png" } },
  // Black & White
  { id: "bw11", name: "Legendary Treasures", series: "Black & White", releaseDate: "2013/11/06", total: 140, images: { symbol: "https://images.pokemontcg.io/bw11/symbol.png", logo: "https://images.pokemontcg.io/bw11/logo.png" } },
  { id: "bw10", name: "Plasma Blast", series: "Black & White", releaseDate: "2013/08/14", total: 105, images: { symbol: "https://images.pokemontcg.io/bw10/symbol.png", logo: "https://images.pokemontcg.io/bw10/logo.png" } },
  { id: "bw9", name: "Plasma Freeze", series: "Black & White", releaseDate: "2013/05/08", total: 122, images: { symbol: "https://images.pokemontcg.io/bw9/symbol.png", logo: "https://images.pokemontcg.io/bw9/logo.png" } },
  { id: "bw8", name: "Plasma Storm", series: "Black & White", releaseDate: "2013/02/06", total: 138, images: { symbol: "https://images.pokemontcg.io/bw8/symbol.png", logo: "https://images.pokemontcg.io/bw8/logo.png" } },
  { id: "bw7", name: "Boundaries Crossed", series: "Black & White", releaseDate: "2012/11/07", total: 153, images: { symbol: "https://images.pokemontcg.io/bw7/symbol.png", logo: "https://images.pokemontcg.io/bw7/logo.png" } },
  { id: "bw6", name: "Dragons Exalted", series: "Black & White", releaseDate: "2012/08/15", total: 128, images: { symbol: "https://images.pokemontcg.io/bw6/symbol.png", logo: "https://images.pokemontcg.io/bw6/logo.png" } },
  { id: "bw5", name: "Dark Explorers", series: "Black & White", releaseDate: "2012/05/09", total: 111, images: { symbol: "https://images.pokemontcg.io/bw5/symbol.png", logo: "https://images.pokemontcg.io/bw5/logo.png" } },
  { id: "bw4", name: "Next Destinies", series: "Black & White", releaseDate: "2012/02/08", total: 103, images: { symbol: "https://images.pokemontcg.io/bw4/symbol.png", logo: "https://images.pokemontcg.io/bw4/logo.png" } },
  { id: "bw3", name: "Noble Victories", series: "Black & White", releaseDate: "2011/11/16", total: 102, images: { symbol: "https://images.pokemontcg.io/bw3/symbol.png", logo: "https://images.pokemontcg.io/bw3/logo.png" } },
  { id: "bw2", name: "Emerging Powers", series: "Black & White", releaseDate: "2011/08/31", total: 98, images: { symbol: "https://images.pokemontcg.io/bw2/symbol.png", logo: "https://images.pokemontcg.io/bw2/logo.png" } },
  { id: "bw1", name: "Black & White", series: "Black & White", releaseDate: "2011/04/25", total: 115, images: { symbol: "https://images.pokemontcg.io/bw1/symbol.png", logo: "https://images.pokemontcg.io/bw1/logo.png" } },
  // HeartGold & SoulSilver
  { id: "hgss4", name: "Triumphant", series: "HeartGold & SoulSilver", releaseDate: "2010/11/03", total: 103, images: { symbol: "https://images.pokemontcg.io/hgss4/symbol.png", logo: "https://images.pokemontcg.io/hgss4/logo.png" } },
  { id: "hgss3", name: "Undaunted", series: "HeartGold & SoulSilver", releaseDate: "2010/08/18", total: 91, images: { symbol: "https://images.pokemontcg.io/hgss3/symbol.png", logo: "https://images.pokemontcg.io/hgss3/logo.png" } },
  { id: "hgss2", name: "Unleashed", series: "HeartGold & SoulSilver", releaseDate: "2010/05/12", total: 96, images: { symbol: "https://images.pokemontcg.io/hgss2/symbol.png", logo: "https://images.pokemontcg.io/hgss2/logo.png" } },
  { id: "hgss1", name: "HeartGold & SoulSilver", series: "HeartGold & SoulSilver", releaseDate: "2010/02/10", total: 124, images: { symbol: "https://images.pokemontcg.io/hgss1/symbol.png", logo: "https://images.pokemontcg.io/hgss1/logo.png" } },
  // Base Sets (Classic)
  { id: "base1", name: "Base Set", series: "Base", releaseDate: "1999/01/09", total: 102, images: { symbol: "https://images.pokemontcg.io/base1/symbol.png", logo: "https://images.pokemontcg.io/base1/logo.png" } },
  { id: "base2", name: "Jungle", series: "Base", releaseDate: "1999/06/16", total: 64, images: { symbol: "https://images.pokemontcg.io/base2/symbol.png", logo: "https://images.pokemontcg.io/base2/logo.png" } },
  { id: "base3", name: "Fossil", series: "Base", releaseDate: "1999/10/10", total: 62, images: { symbol: "https://images.pokemontcg.io/base3/symbol.png", logo: "https://images.pokemontcg.io/base3/logo.png" } },
  { id: "base4", name: "Base Set 2", series: "Base", releaseDate: "2000/02/24", total: 130, images: { symbol: "https://images.pokemontcg.io/base4/symbol.png", logo: "https://images.pokemontcg.io/base4/logo.png" } },
  { id: "base5", name: "Team Rocket", series: "Base", releaseDate: "2000/04/24", total: 83, images: { symbol: "https://images.pokemontcg.io/base5/symbol.png", logo: "https://images.pokemontcg.io/base5/logo.png" } },
  // Gym
  { id: "gym1", name: "Gym Heroes", series: "Gym", releaseDate: "2000/08/14", total: 132, images: { symbol: "https://images.pokemontcg.io/gym1/symbol.png", logo: "https://images.pokemontcg.io/gym1/logo.png" } },
  { id: "gym2", name: "Gym Challenge", series: "Gym", releaseDate: "2000/10/16", total: 132, images: { symbol: "https://images.pokemontcg.io/gym2/symbol.png", logo: "https://images.pokemontcg.io/gym2/logo.png" } },
  // Neo
  { id: "neo1", name: "Neo Genesis", series: "Neo", releaseDate: "2000/12/16", total: 111, images: { symbol: "https://images.pokemontcg.io/neo1/symbol.png", logo: "https://images.pokemontcg.io/neo1/logo.png" } },
  { id: "neo2", name: "Neo Discovery", series: "Neo", releaseDate: "2001/06/01", total: 75, images: { symbol: "https://images.pokemontcg.io/neo2/symbol.png", logo: "https://images.pokemontcg.io/neo2/logo.png" } },
  { id: "neo3", name: "Neo Revelation", series: "Neo", releaseDate: "2001/09/21", total: 66, images: { symbol: "https://images.pokemontcg.io/neo3/symbol.png", logo: "https://images.pokemontcg.io/neo3/logo.png" } },
  { id: "neo4", name: "Neo Destiny", series: "Neo", releaseDate: "2002/02/28", total: 113, images: { symbol: "https://images.pokemontcg.io/neo4/symbol.png", logo: "https://images.pokemontcg.io/neo4/logo.png" } },
  // E-Card
  { id: "ecard1", name: "Expedition", series: "E-Card", releaseDate: "2002/09/15", total: 165, images: { symbol: "https://images.pokemontcg.io/ecard1/symbol.png", logo: "https://images.pokemontcg.io/ecard1/logo.png" } },
  { id: "ecard2", name: "Aquapolis", series: "E-Card", releaseDate: "2003/01/15", total: 186, images: { symbol: "https://images.pokemontcg.io/ecard2/symbol.png", logo: "https://images.pokemontcg.io/ecard2/logo.png" } },
  { id: "ecard3", name: "Skyridge", series: "E-Card", releaseDate: "2003/05/12", total: 182, images: { symbol: "https://images.pokemontcg.io/ecard3/symbol.png", logo: "https://images.pokemontcg.io/ecard3/logo.png" } },
  // EX
  { id: "ex1", name: "Ruby & Sapphire", series: "EX", releaseDate: "2003/07/18", total: 109, images: { symbol: "https://images.pokemontcg.io/ex1/symbol.png", logo: "https://images.pokemontcg.io/ex1/logo.png" } },
  { id: "ex2", name: "Sandstorm", series: "EX", releaseDate: "2003/09/18", total: 100, images: { symbol: "https://images.pokemontcg.io/ex2/symbol.png", logo: "https://images.pokemontcg.io/ex2/logo.png" } },
  { id: "ex3", name: "Dragon", series: "EX", releaseDate: "2003/11/24", total: 100, images: { symbol: "https://images.pokemontcg.io/ex3/symbol.png", logo: "https://images.pokemontcg.io/ex3/logo.png" } },
  // Diamond & Pearl
  { id: "dp1", name: "Diamond & Pearl", series: "Diamond & Pearl", releaseDate: "2007/05/23", total: 130, images: { symbol: "https://images.pokemontcg.io/dp1/symbol.png", logo: "https://images.pokemontcg.io/dp1/logo.png" } },
  { id: "dp2", name: "Mysterious Treasures", series: "Diamond & Pearl", releaseDate: "2007/08/22", total: 124, images: { symbol: "https://images.pokemontcg.io/dp2/symbol.png", logo: "https://images.pokemontcg.io/dp2/logo.png" } },
  { id: "dp3", name: "Secret Wonders", series: "Diamond & Pearl", releaseDate: "2007/11/07", total: 132, images: { symbol: "https://images.pokemontcg.io/dp3/symbol.png", logo: "https://images.pokemontcg.io/dp3/logo.png" } },
  { id: "dp4", name: "Great Encounters", series: "Diamond & Pearl", releaseDate: "2008/02/13", total: 106, images: { symbol: "https://images.pokemontcg.io/dp4/symbol.png", logo: "https://images.pokemontcg.io/dp4/logo.png" } },
  { id: "dp5", name: "Majestic Dawn", series: "Diamond & Pearl", releaseDate: "2008/05/21", total: 100, images: { symbol: "https://images.pokemontcg.io/dp5/symbol.png", logo: "https://images.pokemontcg.io/dp5/logo.png" } },
  { id: "dp6", name: "Legends Awakened", series: "Diamond & Pearl", releaseDate: "2008/08/20", total: 146, images: { symbol: "https://images.pokemontcg.io/dp6/symbol.png", logo: "https://images.pokemontcg.io/dp6/logo.png" } },
  { id: "dp7", name: "Stormfront", series: "Diamond & Pearl", releaseDate: "2008/11/05", total: 106, images: { symbol: "https://images.pokemontcg.io/dp7/symbol.png", logo: "https://images.pokemontcg.io/dp7/logo.png" } },
  // Platinum
  { id: "pl1", name: "Platinum", series: "Platinum", releaseDate: "2009/02/11", total: 133, images: { symbol: "https://images.pokemontcg.io/pl1/symbol.png", logo: "https://images.pokemontcg.io/pl1/logo.png" } },
  { id: "pl2", name: "Rising Rivals", series: "Platinum", releaseDate: "2009/05/20", total: 120, images: { symbol: "https://images.pokemontcg.io/pl2/symbol.png", logo: "https://images.pokemontcg.io/pl2/logo.png" } },
  { id: "pl3", name: "Supreme Victors", series: "Platinum", releaseDate: "2009/08/19", total: 153, images: { symbol: "https://images.pokemontcg.io/pl3/symbol.png", logo: "https://images.pokemontcg.io/pl3/logo.png" } },
  { id: "pl4", name: "Arceus", series: "Platinum", releaseDate: "2009/11/04", total: 111, images: { symbol: "https://images.pokemontcg.io/pl4/symbol.png", logo: "https://images.pokemontcg.io/pl4/logo.png" } },
];

export type FallbackSet = typeof FALLBACK_SETS[number];
